  # See http://www.appveyor.com/docs/appveyor-yml for many more options

build: false
version: 0.1.{build}

#images 

image: 
  - Ubuntu1804
  - Visual Studio 2017

# Set build info
environment:
  environment: development
  version: 0.1.$(appveyor_build_number)
  mysql_login: root
  mysql_password: Password12!

  matrix:
  - scenario: ALL
  - scenario: mysql


for:
  - matrix:
      only:
        - image: Visual Studio 2017
          scenario: ALL
    environment:
        mssql_instance: localhost\SQL2017
    services:
      - mssql2017

  - matrix:
      only:
        - image: Ubuntu1804
          scenario: ALL
    environment:
        mssql_instance: localhost
        mssql_login: sa
        mssql_password: Password12!
    services:
      - mssql

  - matrix:
      only:
        - image: Visual Studio 2017
          scenario: mysql
    services:
      - mysql

  - matrix:
      only:
        - image: Ubuntu1804
          scenario: mysql
    services:
      - mysql



before_test:
  # run preparation scripts
  - ps: .\tests\appveyor.prep.ps1
test_script:
  # Test with native PS version
  - ps: .\tests\appveyor.pester.ps1
  # Collecting results
  - ps: .\tests\appveyor.pester.ps1 -Finalize
after_test:
  - ps: .\tests\appveyor.post.ps1  

  
# Set alternative clone folder
#clone_folder: c:\github\dbops



#on_finish:
#  - ps:
